### ISSUE TITLE
Corrupted dataset

### ISSUE THREAD

**Issue by AndersonCotrim** [ulaval-damas/tree-bark-classification#3]
Hi,

First of all, thanks for sharing this BarkNet 1.0 dataset : )

It seems a corruption problem in the zip dataset, for the linux system i got the error message:
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

I'm commited to work in a college project with yours data, it will be very useful it can be fixed as soon as possible

Thanks.

**Comment by ulavalrobotics** [comment]
Check https://data.mendeley.com/datasets?query=Barknet



I have recently uploaded a dezipped version of the dataset on mendeley. Due to the size, it's broken in four parts.





Philippe Giguère


(envoyé par mobile/sent from phone)





On Sun, Sep 22, 2019 at 3:27 PM -0400, "AndersonCotrim" 
<notifications@github.com> wrote:



Hi,
First of all, thanks for sharing this BarkNet 1.0 dataset : )
It seems a corruption problem in the zip dataset, for the linux system i got the error message:
End-of-central-directory signature not found. Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive. In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
I'm commited to work in a college project with yours data, it will be very useful it can be fixed as soon as possible
Thanks.
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ulaval-damas/tree-bark-classification/issues/3?email_source=notifications\u0026email_token=ABT6EJOOLBWU2ANVQNO45VLQK7BJBA5CNFSM4IZEEUPKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HM44XLA",
"url": "https://github.com/ulaval-damas/tree-bark-classification/issues/3?email_source=notifications\u0026email_token=ABT6EJOOLBWU2ANVQNO45VLQK7BJBA5CNFSM4IZEEUPKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HM44XLA",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ulavalrobotics** [comment]
I have rezipped the database here : https://storage.googleapis.com/barknet-1/BarkNet%201.0.zip

**Comment by AndersonCotrim** [comment]
Hi, thanks for replying. The crc problem was solved, but the new zip file only have 21 folders (classes), it is missing BOJ and BOP. Is it possible fix it?

Thanks.

**Comment by ulavalrobotics** [comment]
Hopefully this time it’s good!

I restarted everything from scratch. Now the BOP and BOJ folders are in the .zip file.
https://storage.googleapis.com/barknet-1/BarkNet%201.0.zip

Best,

Philippe

**Comment by AndersonCotrim** [comment]
Hi again, thanks for helping. But now we have another problem, some files are corrupted in BOP and BOJ folder, there are few of them like 463_BOJ_56_GalaxyS5_20170607_154320_32.jpg (the training code doesn't work due this). Anyaway as there are few  of them, I have just delete them and now I can start the experiments. I think it will not be a big problem, just to report that there is this problem in dataset.

**Comment by ulavalrobotics** [comment]
I have reuploaded a newer version, named it 1.001. I have manually checked now that the BOJ and BOP did not contain corrupt data. For some reason, I had corrupted versions on my desktop, and went back to the original disk.

Philippe
